name: release

on: push

jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra;
          wget https://github.com/jgm/pandoc/releases/download/2.16.2/pandoc-2.16.2-1-amd64.deb
          sudo dpkg -i pandoc-2.16.2-1-amd64.deb
      - name: Generate build artifacts
        run: cd pdf && make
      - name: Create release
        id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        with:
          args: 'pdf/*.pdf'
          releaseId: ${{ steps.release.outputs.tag_name }}