name: release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y pandoc texlive-latex-base texlive-latex-recommended texlive-latex-extra
      - name: Update TeX
        run: tlmgr init-usertree && tlmgr update --self
      - name: Install required TeX dependencies
        run: sudo tlmgr install titlesec
      - name: Generate build artifacts
        run: cd pdf && make